development:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: serviceServer_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: serviceServer_production
